hostname: 'robotino1'
mobile: true
holonomic: true
location: {x: 10.0, y: 5.0, theta: deg(0.0)}
skill0: {resource: {name: 'velocity', description: 'robot velocity'}, level: 'resourceful'}
skill1: {resource: {name: 'strength', description: 'robot strength'}, level: 'resourceful'}
skill2: {resource: {name: 'flexibility', description: 'robot has flexible movements'}, level: 'resourceful'}
skill3: {resource: {name: 'smoothness', description: 'robot can drive smoothly'}, level: 'resourceful'}
skill4: {resource: {name: 'vision', description: 'robot implement computer vision algorithms'}, level: 'resourceful'}
