hostname: 'robotino3'
mobile: true
holonomic: true
location: {x: 15.0, y: 15.0, theta: deg(45.0)}
skill0: {resource: {name: 'velocity', description: 'robot velocity'}, level: 'moderate'} 
skill1: {resource: {name: 'strength', description: 'robot strength'}, level: 'resourceful'} 
skill2: {resource: {name: 'flexibility', description: 'robot has flexible movements'}, level: 'low'} 
