string hostname

---

bool valid					# true if input hostname is a registered robot, otherwise it is false
string message
mrs_msgs/Agent robot				# when robot is valid
bool logged					# true if this robot is logged, otherwise it is false



