string name

---

bool valid					# true if input name is a registered user, otherwise it is false
string message
mrta_vc/Agent user				# when user is valid
bool logged					# true if this user is logged, otherwise it is false



